version: "3.8"

services:
  api-node:
    build:
      context: ../../back-end
      dockerfile: ../docker/dev/requirements/api-node/Dockerfile
    volumes:
      - ../../back-end:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  web-node:
    build:
      context: ../../front-end
      dockerfile: ../docker/dev/requirements/web-node/Dockerfile
    volumes:
      - ../../front-end:/app
    environment:
      DATABASE_URL: http://api-node:3000
    ports:
      - "80:4000"
    depends_on:
      - api-node
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
volumes:
  db-data:
