version: '3.8'

services:
  node:
    build:
      context: ../../
      dockerfile: ./docker/prod/requirements/node/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
volumes:
  db-data:
